### PR TITLE
Add portable Node.js guide

### PR DESCRIPTION
**Pull request by ehmicky**

### CODE REVIEW

**Review by tejasrsuthar — APPROVED** [review]

**Comment by tejasrsuthar** [comment]
Hey @ehmicky, would you please resolve the conflicts? So I can merge your PR.

**Comment by ehmicky** [comment]
Hi @tejasrsuthar, done. Thanks!

**Comment by ehmicky** [comment]
You might need to re-open the PR though.

**Comment by tejasrsuthar** [comment]
@ehmicky 
Not Able to reopen the PR. Could you please create a new one?

**Comment by ehmicky** [comment]
Done at #7

**Pull request closed without merging**
